[features]
seeds = false
[programs.localnet]
next_level_ido_platform = "EQQc7CVfiLnSPkA1T4ddTSBbVjv39uWgtRGNJssp61a3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/khacvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
seed = "yarn run ts-node tests/seed.ts"